#!/bin/sh

BINDIR=$(dirname $0)

case "$1" in
  start)
    $BINDIR/dbus/agile-dbus-start
    $BINDIR/compose/agile-compose up -d agile-core
    sleep 10
    $BINDIR/compose/agile-compose up -d agile-ui
    sleep 10
    $BINDIR/compose/agile-compose up -d agile-osjs
    sleep 10
    $BINDIR/compose/agile-compose up -d
    ;;
  stop)
    $BINDIR/dbus/agile-dbus-stop
    $BINDIR/compose/agile-compose down
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  update)
    $BINDIR/compose/agile-compose pull
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|update}"
    exit 1
    ;;
esac
