#!/bin/sh

ARCH=$(uname -m)
IMAGE=${1:-cskiraly/agile-core-$ARCH}
BINDIR=$(dirname $0)
DBUS_AGILE_BUS_ADDRESS="$HOME/agile_bus_socket2"

DOCKER_COMMON="\
  -d \
  --security-opt apparmor:unconfined \
  -v $DBUS_AGILE_BUS_ADDRESS:/usr/src/app/agile_bus_socket \
  -e DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/agile_bus_socket
"

dbus-daemon \
  --fork \
  --print-pid --print-address \
  --address=unix:path=$DBUS_AGILE_BUS_ADDRESS \
  --config-file=$BINDIR/../dbus/agile.conf

NAME=agile-core-BLE
docker rm $NAME
docker run \
  $DOCKER_COMMON \
  -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
  --name $NAME \
  $IMAGE scripts/start.sh BLE

NAME=agile-core-ProtocolManager
docker rm $NAME
docker run \
  $DOCKER_COMMON \
  --name $NAME \
  $IMAGE scripts/start.sh ProtocolManager

NAME=agile-core-DeviceManager
docker rm $NAME
docker run \
  $DOCKER_COMMON \
  --name $NAME \
  $IMAGE scripts/start.sh DeviceManager

NAME=agile-core-http
docker rm $NAME
docker run \
  $DOCKER_COMMON \
  -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
  -p 8080:8080/tcp \
  --name $NAME \
  $IMAGE scripts/start.sh http
