#!/bin/sh

BINDIR=$(dirname $0)

case "$1" in
  start)
    $BINDIR/agile-core-perservice-start
    $BINDIR/agile-influxdb-start
    $BINDIR/agile-grafana-start
    $BINDIR/agile-nodered-start
    $BINDIR/agile-osjs-start
    ;;
  stop)
    #$BINDIR/agile-stop
    docker stop agile-core-http
    docker stop agile-core-ProtocolManager
    docker stop agile-core-DeviceManager
    docker stop agile-core-BLE
    docker stop agile-osjs
    docker stop agile-nodered
    docker stop agile-grafana
    docker stop agile-influxdb
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  update)
    docker pull agileiot/agile-core-armv7l
    docker pull agileiot/agile-zb-armv7l
    docker pull agileiot/agile-osjs-armv7l
    docker pull agileiot/agile-nodered-armv7l
    docker pull fg2it/grafana-armhf:v3.1.1
    docker pull sbiermann/rpi-influxdb
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|update}"
    exit 1
esac
