#!/bin/sh

ARCH=$(uname -m)
IMAGE=${1:-cskiraly/agile-core-$ARCH}
BINDIR=$(dirname $0)
DBUS_AGILE_BUS_ADDRESS="$HOME/agile_bus_socket2"

dbus-daemon \
  --fork \
  --print-pid --print-address \
  --address=unix:path=$DBUS_AGILE_BUS_ADDRESS \
  --config-file=$BINDIR/../dbus/agile.conf

docker run \
  -d \
  -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
  --security-opt apparmor:unconfined \
  -p 8080:8080/tcp \
  -v $DBUS_AGILE_BUS_ADDRESS:/usr/src/app/agile_bus_socket \
  -e DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/agile_bus_socket \
  $IMAGE
