#!/bin/sh

DOCKER_COMMON="\
  -d \
  --security-opt apparmor:unconfined \
  -v $HOME/agile_bus_socket:/usr/src/app/agile_bus_socket \
  -e DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/agile_bus_socket
"

dbus-daemon \
  --fork \
  --print-pid --print-address \
  --address=unix:path=$HOME/agile_bus_socket \
  --config-file=dbus/agile.conf

docker run \
  $DOCKER_COMMON \
  -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
  $1 scripts/start.sh BLE

docker run \
  $DOCKER_COMMON \
  $1 scripts/start.sh ProtocolManager

docker run \
  $DOCKER_COMMON \
  $1 scripts/start.sh DeviceManager

docker run \
  $DOCKER_COMMON \
  -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
  -p 8080:8080/tcp \
  $1 scripts/start.sh http
